#!/usr/bin/env python3
"""AST-parse register_*_ci(...) decorators from test files; emit a Starlark
registry that tools/pytest.bzl reads to apply suite/est_time tags to each
generated py_test target.

This is the Phase-0.5 codegen tool that bridges sglang's existing
test/run_suite.py registry (in python/sglang/test/ci/ci_register.py) to
Bazel's tag-based selection.

Usage
-----
    python3 scripts/ci/generate_bazel_tags.py
        # writes tools/sglang_test_registry.bzl

    python3 scripts/ci/generate_bazel_tags.py --check
        # exits 1 if the file is out of date (for pre-commit / CI gating)

Output schema
-------------
    SGLANG_TEST_REGISTRY = {
        "test/registered/quant/test_int8_kernel.py": {
            "suite": "stage-b-test-1-gpu-small",
            "est_time": 15,
            "nightly": False,
        },
        ...
    }

Limitations
-----------
- Only parses literal arguments. `register_cuda_ci(est_time=foo)` (variable
  reference) is silently skipped with a stderr warning.
- When a file has both register_cuda_ci and register_amd_ci, the cuda
  registration wins. AMD-specific suites are lost in the demo registry.
- `disabled=True` registrations are skipped entirely (those tests don't run).
"""

from __future__ import annotations

import argparse
import ast
import sys
from dataclasses import dataclass
from pathlib import Path

# Hardware-specific decorators we care about, in priority order. Cuda first
# so CI tests that have both cuda+amd registrations get cuda metadata.
_HW_FUNCS = (
    "register_cuda_ci",
    "register_cpu_ci",
    "register_amd_ci",
    "register_npu_ci",
)

# Roots to scan. These match test/run_suite.py's `collect_tests` discovery.
_TEST_ROOTS = ("test/registered", "test/srt", "test/manual")


@dataclass
class _Reg:
    suite: str
    est_time: int
    nightly: bool


def _eval_kwargs(call: ast.Call, file: Path) -> dict[str, object] | None:
    """Extract kwargs from an ast.Call where every value is a literal.

    Returns None if any kwarg is a non-literal (we can't evaluate at codegen
    time). This is rare in practice — sglang's CI registrations are almost
    all literal — but we warn when it happens.
    """
    out: dict[str, object] = {}
    for kw in call.keywords:
        if kw.arg is None:  # **kwargs splat
            return None
        try:
            out[kw.arg] = ast.literal_eval(kw.value)
        except (ValueError, SyntaxError):
            sys.stderr.write(
                f"WARN: {file}:{kw.lineno} — non-literal value for "
                f"'{kw.arg}', skipping this registration\n"
            )
            return None
    return out


def _extract_first_registration(file: Path) -> _Reg | None:
    """Find the first register_<hw>_ci(...) call at module scope.

    Returns None if the file has no registration, or if the registration
    has `disabled=True`, or if any kwarg is non-literal.
    """
    try:
        tree = ast.parse(file.read_text())
    except (SyntaxError, UnicodeDecodeError):
        return None

    by_hw: dict[str, _Reg] = {}
    for node in tree.body:
        if not isinstance(node, ast.Expr) or not isinstance(node.value, ast.Call):
            continue
        call = node.value
        if not isinstance(call.func, ast.Name) or call.func.id not in _HW_FUNCS:
            continue
        kwargs = _eval_kwargs(call, file)
        if kwargs is None or kwargs.get("disabled"):
            continue
        suite = kwargs.get("suite")
        est_time = kwargs.get("est_time")
        if not isinstance(suite, str) or not isinstance(est_time, int):
            continue
        by_hw[call.func.id] = _Reg(
            suite=suite,
            est_time=est_time,
            nightly=bool(kwargs.get("nightly", False)),
        )

    # Cuda > cpu > amd > npu; pick the highest-priority entry that exists.
    for hw in _HW_FUNCS:
        if hw in by_hw:
            return by_hw[hw]
    return None


def _format_starlark(registry: dict[str, _Reg], repo_root: Path) -> str:
    lines = [
        '"""GENERATED by scripts/ci/generate_bazel_tags.py — do not edit by hand.',
        "",
        "Maps each test file's repo-relative path to its register_*_ci metadata,",
        "consumed by tools/pytest.bzl to set per-target Bazel tags.",
        '"""',
        "",
        "SGLANG_TEST_REGISTRY = {",
    ]
    for path in sorted(registry):
        r = registry[path]
        lines.append(f'    "{path}": {{')
        lines.append(f'        "suite": "{r.suite}",')
        lines.append(f'        "est_time": {r.est_time},')
        lines.append(f'        "nightly": {str(r.nightly)},')
        lines.append("    },")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def _build_registry(repo_root: Path) -> dict[str, _Reg]:
    registry: dict[str, _Reg] = {}
    for root in _TEST_ROOTS:
        root_path = repo_root / root
        if not root_path.exists():
            continue
        for file in root_path.rglob("test_*.py"):
            reg = _extract_first_registration(file)
            if reg is None:
                continue
            registry[str(file.relative_to(repo_root))] = reg
    return registry


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail with exit 1 if the output file is stale (for pre-commit / CI).",
    )
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[2]
    registry = _build_registry(repo_root)
    output = _format_starlark(registry, repo_root)

    target = repo_root / "tools" / "sglang_test_registry.bzl"

    if args.check:
        existing = target.read_text() if target.exists() else ""
        if existing != output:
            sys.stderr.write(
                f"ERROR: {target.relative_to(repo_root)} is out of date. "
                f"Re-run `python3 scripts/ci/generate_bazel_tags.py`.\n"
            )
            return 1
        sys.stderr.write(f"OK: {target.relative_to(repo_root)} matches sources\n")
        return 0

    target.write_text(output)
    sys.stderr.write(
        f"Wrote {target.relative_to(repo_root)} ({len(registry)} entries)\n"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
